### ISSUE TITLE
EVA system not quite compatible with Endorphin

### ISSUE THREAD

**Issue by TristanPeers** [endorphin3d/endorphin#3]
Hi - the EVA system is not compatible without some modification (sadly the setup you have listed does not work as is).

Firstly many thanks for creating this system!!!

I did stage 1 first a few weeks back and everything was working fine. I changed the kinematics to `hybrid_corexy` - all good. I printed all the parts for stage 2/3 and EVA on this new setup - no issues.

I've just tried to do stages 2/3 with the EVA carriage this weekend.

Sadly the first problem is that X became reversed. I changed the X `dir_pin` to fix this, but then when you move Y, X also moves at the same time.

This is exactly the same as this person reports (see my comments): https://www.reddit.com/r/ender5/comments/169eomj/endorphin_y_motion/

The problem is that the belt attachments for the EVA setup with Endorphin are on the [back](https://github.com/endorphin3d/endorphin/blob/main/docs/stages/stage-3.md?plain=1#L97-L101). As you can see from the Reddit thread above the person has decided to update his `hybrid_corexy` python code to combat this.

I have opted for the simpler approach of moving the belt attachment to the front however the EVA front attachment with the current Endorphin parts cause the belt to rub.

Just thought I'd let you know.

**Comment by endorphin3d** [comment]
Ok, I think I know the issue you guys are facing because I ran the EVA for a good while without any issues. I think rather than inverting the pin, you need to tell Klipper the endstops are on the other end (200 rather than 0). Here's my Klipper config for X and Y:

```yml
[stepper_x]
step_pin: PB9
dir_pin: PC2
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA5
position_endstop: 220
position_max: 220
homing_speed: 50

[stepper_y]
step_pin: PB7
dir_pin: PB8
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA6
position_endstop: 200
position_max: 200
homing_speed: 50
```

If you do this with the belt on the back and this fixes things, I'll update the docs that `position_endstop` should be `200`.

**Comment by TristanPeers** [comment]
Hi - sorry, that's not the issue. My config is pretty much identical to yours and my endstops are also on the end of the axes (position_max):

```ini
[stepper_x]
step_pin: PB9
dir_pin: PC2
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA5
position_endstop: 220
position_max: 220
homing_speed: 50
homing_retract_dist: 0

[stepper_y]
step_pin: PB7
dir_pin: PB8
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: ^PA6
position_endstop: 190
position_max: 190
homing_speed: 50
homing_retract_dist: 0
```

This config above is what I had running with stage 1.

As soon as I installed the EVA carriage (with the belt attached on the back) and turned the printer on with the config above, X was reversed. It tried to home on the left of the printer. And the X movements were reversed in Fluidd. Pressing right in the console moved the carriage left and vice versa.

As X was now reversed, I changed it to:

```ini
[stepper_x]
step_pin: PB9
dir_pin: !PC2
...
```

And X behaved correctly....however when moving Y, it also moves X at the same time.
Moving the belt attachment to the front has fixed the issue (keeping the config above, not the inverted `dir_pin`)

**Comment by endorphin3d** [comment]
Okay I see. As I now am running the Vz printhead with the belts at the front, I don't know exactly what my config looked like when I had the EVA, but I'm curious what would happen if you changed the X settings to the following:

```yml
[stepper_x]
step_pin: PB9
dir_pin: PC2
position_endstop: 0
position_max: 220
```
